### ISSUE TITLE
Leg is inverse

### ISSUE THREAD

**Issue by phields** [duo-inc/EasyMotionRecorder#13]
![image](https://user-images.githubusercontent.com/31947421/50549142-64f44780-0c92-11e9-97b5-40d70219c0cc.png)

**Comment by phields** [comment]
This issue Happened when your use timeline or enable Foot IK in the animation.

**Comment by phields** [comment]
![before](https://user-images.githubusercontent.com/31947421/51138605-7d608680-187c-11e9-8041-d749717be5ee.gif)

**Comment by phields** [comment]
![image](https://user-images.githubusercontent.com/31947421/51138730-d16b6b00-187c-11e9-8d20-4b489f881e10.png)
Fixed with add extra IK info in the asset file.
![before](https://user-images.githubusercontent.com/31947421/51138843-332bd500-187d-11e9-8921-244a08b03032.gif)

**Comment by phields** [comment]
@tomori-hikage 
https://github.com/duo-inc/EasyMotionRecorder/pull/16
Hi, I've pulled the branch.

**Comment by tomori-hikage** [comment]
Thanks!
