### ISSUE TITLE
Record take too much frames in 1.1.0

### ISSUE THREAD

**Issue by phields** [duo-inc/EasyMotionRecorder#15]
![image](https://user-images.githubusercontent.com/31947421/51134349-46857300-1872-11e9-88ed-0961da4f7fe6.png)

BTW I'm trying to fix Timeline problem(https://github.com/duo-inc/EasyMotionRecorder/issues/13)
It's caused by the Foot IK system. 
I'll pull that patch whit this face record version.

**Comment by phields** [comment]
Problem solved!
Just **don't** use realtimeSinceStartup instead of deltaTime.....
https://github.com/duo-inc/EasyMotionRecorder/commit/6a0f2924da97997315db18bc5ce655ebe0b9b789#diff-6f9ff50a996f7e953884a84c00c4e58cR87

**Comment by tomori-hikage** [comment]
I would be happy if you send us a pull request if you do not mind!
