### ISSUE TITLE
BlendshapeRecorder out of sync with RecordMotion Clip

### ISSUE THREAD

**Issue by phields** [duo-inc/EasyMotionRecorder#17]
![image](https://user-images.githubusercontent.com/31947421/51189209-843dd680-191a-11e9-97dc-92117c18451e.png)
And there is some “curves problem”.
If one blendshape change to 100 the change to 0 before 1 second, the curves should like that:
![image](https://user-images.githubusercontent.com/31947421/51189663-76d51c00-191b-11e9-9693-6f8555d3ea49.png)
but curves become that:
![image](https://user-images.githubusercontent.com/31947421/51189689-82284780-191b-11e9-9490-d5d18a9c009a.png)

**Comment by entum** [comment]
#25 fix_issue_17 (facial recording problem)

Resolved by this pull request.
Thanks!
